### ISSUE TITLE
Code error returns " 'oneAfterAnother' was not declared in this scope "

### ISSUE THREAD

**Issue by SFERob** [sparkfun/SIK-Guide-Code#23]
In experiment #14, SIK_circuit14_shiftRegister, line 89 is missing an open bracket at the end of the line. Should read

void shiftWrite(int desiredPin, boolean desiredState){

THanks!

Rob Reynolds

**Comment by ToniCorinne** [comment]
@JoelEB throwing you on this in case changing this affects your current work in any way. Thanks!

**Comment by ToniCorinne** [comment]
Adding @bboyho to verify this on the errata sheet.

**Comment by bboyho** [comment]
Yeah, it looks like it is missing the curly bracket in the v3.3 circuit 14 example => [ https://github.com/sparkfun/SIK-Guide-Code/blob/v33/SIK_circuit14_shiftRegister/SIK_circuit14_shiftRegister.ino#L90 . I'm not sure how to fix the code in an older branch now that we have SIK v4.0a?

**Comment by bboyho** [comment]
It's a GitHub rabbit hole if we go back to a tag version to fix. Since v3.3 is retired and we are using v4.0, it will not be fixed in the tag. The least that I have done is add a won't fix label and added a note in the SIK v3.3. The example code in the tutorial [ [https://learn.sparkfun.com/tutorials/sik-experiment-guide-for-arduino---v33/experiment-14-using-a-shift-register(https://learn.sparkfun.com/tutorials/sik-experiment-guide-for-arduino---v33/experiment-14-using-a-shift-register) ] is fine.
