### ISSUE TITLE
Pin assignment error

### ISSUE THREAD

**Issue by SFERob** [sparkfun/SIK-Guide-Code#27]
Pin assignments for echoPin and trigPin (code lines 14-15) are inconsistent with the wiring diagram in the hookup guides, both printed and online. To match code for experiment 3C, code should read

 ```
const int trigPin = 11;           //connects to the trigger pin on the distance sensor 
 const int echoPin = 12;           //connects to the echo pin on the distance sensor   
```

Thanks!

**Comment by ToniCorinne** [comment]
@bboyho have this been addressed with the errata sheet?

**Comment by bboyho** [comment]
### Ultrasonic Sensor Pins
It looks like Joel had caught the ultrasonic sensor's pin definition for SIK v4.0a. It was reported in tech support a while back and placed into a document to fix. I didn't realize that there was an issue filed in the GitHub repo until now. This has been fixed in the printed and online version. However, it was not addressed in the SIK Errata [ [https://www.sparkfun.com/SIKerrata](https://www.sparkfun.com/SIKerrata) ].

**Comment by bboyho** [comment]
This issue has been fixed in the code for the tutorial and GitHub repo. Users should not notice a difference if they are using the code with the circuit illustrated in the guide book. It is not necessary to add this into the errata sheet because the printed guide was not modified.
